# This is a basic workflow to help you get started with Actions 

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: main
 
      - name: Checkout destination rep
        uses: actions/checkout@v2
        with:
          repository: cchowthi/m-mkvenv
          token: ${{ secrets.cchowthi_pat }}
          path: m-mkvenv
          
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Create python module.
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          cd main
          python setup.py sdist bdist_wheel
          cd dist
          latest=$(ls -t *gz | head -n1)
          echo Latest distribution is $latest
          module=${latest%-*}
          echo Replacing the previous $module module with the latest
          rm ../../m-mkvenv/$module*gz
          cp *gz ../../m-mkvenv
          
      - name: Commit to destination repo
        run: |
          cd m-mkvenv
          ls -l
          git config --global user.name "${{ secrets.my_name }}"
          git config --global user.email  "${{ secrets.my_email }}"
          git fetch
          git checkout main
          git add *gz
          git commit -m "Automatic update of m-mkvenv"
          git push
